[package]
name = "probabilistic_robotics"
version = "0.1.0"
authors = ["Haruki Uchiito <uhcahriuiktio0114@outlook.com>"]
edition = "2018"

[dependencies]
gnuplot = "0.0.30"
rand = "*"
rand_distr = "*"
h_analyzer_client_lib = { git = "https://github.com/HarukiUchito/h_analyzer_client_lib.git" }
